In [10]:
from math import radians
import numpy as np
import scipy.linalg as splin

In [2]:
print(f'numpy: {np.__version__}')
#np.show_config()
print(f'scipy: {scipy.__version__}')

numpy: 1.14.2
scipy: 1.0.1


In [3]:
# ----- numpy arrays --------------
# Create a vector as a row
print('row vector:')
vector_row = np.array([1, 2, 3])
print(vector_row)

# Create a vector as a row
print('column vector:')
vector_column = np.array([[1], [2], [3]])
print(vector_column)

# create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(matrix)

row vector:
[1 2 3]
column vector:
[[1]
 [2]
 [3]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#------- math ----------------
r = 192500
# travel distance from Moon over 15 rad
dist = r*radians(15)
print("distance = " + str(dist))

distance = 50396.38215133626


In [5]:
vector_row*radians(10)

array([0.17453293, 0.34906585, 0.52359878])

In [6]:
# create range from 0 to 11
a = np.arange(12).reshape(3,4)
print("a:")
print(a)
print("a.shape: ", str(a.shape))
print("a.ndim: ", str(a.ndim))
print("a.dtype.name: ", str(a.dtype.name))
print("a.itemsize: ", str(a.itemsize))
print("type(a): ", type(a))
print('tranpose(a):')
print(a.T)

a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a.shape:  (3, 4)
a.ndim:  2
a.dtype.name:  int32
a.itemsize:  4
type(a):  <class 'numpy.ndarray'>
tranpose(a):
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [11]:
b = np.array([(1.5,2), (4,5)])
print("b:")
print(b)

# ---- matrix operations
print('b.inverse (numpy):')
print(np.linalg.inv(b))
print('b inverse (scipy):')
print(splin.inv(b))
# Return determinant of matrix
print('det(b) (numpy):')
print(np.linalg.det(b))
print('det(b) (scipy):')
print(splin.det(b))

print("b**2")
print(np.square(b))
print('mean, variance, and stdev of b')
print(np.mean(b), np.var(b), np.std(b))

b:
[[1.5 2. ]
 [4.  5. ]]
b.inverse (numpy):
[[-10.   4.]
 [  8.  -3.]]
b inverse (scipy):
[[-10.   4.]
 [  8.  -3.]]
det(b) (numpy):
-0.5000000000000001
det(b) (scipy):
-0.5
b**2
[[ 2.25  4.  ]
 [16.   25.  ]]
mean, variance, and stdev of b
3.125 2.046875 1.4306903927824497


In [ ]:
c = np.array([[4.5,3.2],[5.3,7.7]])
c


In [ ]:
print("b+c")
print(b+c)
print("b*c")
print(b*c)
print("b.dot(c) is same as np.dot(b,c)")
print(b.dot(c))

In [ ]:
# create 10 ticks between 0 and 2pi
e = np.linspace(0,2*np.pi,10)
e

In [ ]:
f = np.sin(e)
f

In [ ]:
g = np.eye(3)
print("identity matrix 3x3:")
print(g)

iden5 = np.identity(5)
print('identity matrix 5x5:')
print(iden5)

In [ ]:
h = np.random.random((3,3,3))
print("h:")
print(h)
print("h.mean(): ", str(h.mean()))

In [ ]:
print("0*np.nan: ", 0 * np.nan)
print("np.nan == np.nan: ", np.nan == np.nan)
print("np.inf > np.nan: ", np.inf > np.nan)
print("np.nan - np.nan: ", np.nan - np.nan)

In [ ]:
# Create a function that adds 100 to something
add_100 = lambda i: i + 100

print('vectorize:')
# Create a vectorized function
vectorized_add_100 = np.vectorize(add_100)

vectorized_add_100(matrix)

In [ ]:
height_weight = [[74.,210.],[71.,189.],[73.,182.],[75.,224.],\
                 [71.,142.],[75.,180.],[69.,165.4],[85.,244.]]
print('height, weight:')
print(height_weight)
np_height_weight = np.array(height_weight)
print(np_height_weight)
print('3rd row:')
print(np_height_weight[2,:])
print('2nd col:')
print(np_height_weight[:,1])
conversion = np.array([0.0254,0.453592])
print('converted height and weight:')
print(conversion*np_height_weight)

In [12]:
#----------- inverse matrices
import time

dims = [50, 100, 1000]

for n in dims:
    print('-----{}x{}-----'.format(n,n))
    mat = np.random.random((n,n))*10
    print('scipy linalg inv:')
    tic = time.process_time()
    inv1 = splin.inv(mat)
    toc = time.process_time()
    t_scipy = toc-tic
    print('time used: {}'.format(t_scipy))
    print('numpy linalg inv:')
    tic = time.process_time()
    inv1 = np.linalg.inv(mat)
    toc = time.process_time()
    t_numpy = toc-tic
    print('time used: {}'.format(t_numpy))
    #print('t_scipy/t_numpy = {:.3f}'.format(t_scipy/t_numpy))

-----50x50-----
scipy linalg inv:
time used: 0.0
numpy linalg inv:
time used: 0.0
-----100x100-----
scipy linalg inv:
time used: 0.015625
numpy linalg inv:
time used: 0.0
-----1000x1000-----
scipy linalg inv:
time used: 0.15625
numpy linalg inv:
time used: 0.328125
