In [28]:
from math import radians
import numpy as np
import scipy

In [30]:
print(f'numpy: {np.__version__}')
#np.show_config()
print(f'scipy: {scipy.__version__}')

numpy: 1.14.2
scipy: 1.0.1


In [18]:
# ----- numpy arrays --------------
# Create a vector as a row
print('row vector:')
vector_row = np.array([1, 2, 3])
print(vector_row)

# Create a vector as a row
print('column vector:')
vector_column = np.array([[1], [2], [3]])
print(vector_column)

# create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(matrix)

row vector:
[1 2 3]
column vector:
[[1]
 [2]
 [3]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#------- math ----------------
r = 192500
# travel distance from Moon over 15 rad
dist = r*radians(15)
print("distance = " + str(dist))

distance = 50396.38215133626


In [5]:
vector_row*radians(10)

array([0.17453293, 0.34906585, 0.52359878])

In [6]:
# create range from 0 to 11
a = np.arange(12).reshape(3,4)
print("a:")
print(a)
print("a.shape: ", str(a.shape))
print("a.ndim: ", str(a.ndim))
print("a.dtype.name: ", str(a.dtype.name))
print("a.itemsize: ", str(a.itemsize))
print("type(a): ", type(a))
print('tranpose(a):')
print(a.T)

a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a.shape:  (3, 4)
a.ndim:  2
a.dtype.name:  int32
a.itemsize:  4
type(a):  <class 'numpy.ndarray'>
tranpose(a):
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [31]:
b = np.array([(1.5,2), (4,5)])
print("b:")
print(b)

# ---- matrix operations
print('b.inverse (numpy):')
print(np.linalg.inv(b))
print('b inverse (scipy):')
print(scipy.linalg.inv(b))
# Return determinant of matrix
print('det(b) (numpy):')
print(np.linalg.det(b))
print('det(b) (scipy):')
print(scipy.linalg.det(b))

print("b**2")
print(np.square(b))
print('mean, variance, and stdev of b')
print(np.mean(b), np.var(b), np.std(b))

b:
[[1.5 2. ]
 [4.  5. ]]
b.inverse (numpy):
[[-10.   4.]
 [  8.  -3.]]
b inverse (scipy):
[[-10.   4.]
 [  8.  -3.]]
det(b) (numpy):
-0.5000000000000001
det(b) (scipy):
-0.5
b**2
[[ 2.25  4.  ]
 [16.   25.  ]]
mean, variance, and stdev of b
3.125 2.046875 1.4306903927824497


In [8]:
c = np.array([[4.5,3.2],[5.3,7.7]])
c


array([[4.5, 3.2],
       [5.3, 7.7]])

In [9]:
print("b+c")
print(b+c)
print("b*c")
print(b*c)
print("b.dot(c) is same as np.dot(b,c)")
print(b.dot(c))

b+c
[[ 6.   5.2]
 [ 9.3 12.7]]
b*c
[[ 6.75  6.4 ]
 [21.2  38.5 ]]
b.dot(c) is same as np.dot(b,c)
[[17.35 20.2 ]
 [44.5  51.3 ]]


In [10]:
# create 10 ticks between 0 and 2pi
e = np.linspace(0,2*np.pi,10)
e

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [11]:
f = np.sin(e)
f

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

In [13]:
g = np.eye(3)
print("identity matrix 3x3:")
print(g)

iden5 = np.identity(5)
print('identity matrix 5x5:')
print(iden5)

identity matrix 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
identity matrix 5x5:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
h = np.random.random((3,3,3))
print("h:")
print(h)
print("h.mean(): ", str(h.mean()))

h:
[[[0.61411746 0.23631496 0.5245462 ]
  [0.14803362 0.47141887 0.91555018]
  [0.34544369 0.01648243 0.39161724]]

 [[0.05913007 0.75618607 0.02716551]
  [0.85926998 0.16767692 0.89899213]
  [0.91251514 0.06189858 0.44136495]]

 [[0.58389841 0.64961501 0.99378624]
  [0.13727408 0.62080186 0.31707234]
  [0.96148443 0.28075344 0.04121173]]]
h.mean():  0.46050450117682984


In [15]:
print("0*np.nan: ", 0 * np.nan)
print("np.nan == np.nan: ", np.nan == np.nan)
print("np.inf > np.nan: ", np.inf > np.nan)
print("np.nan - np.nan: ", np.nan - np.nan)

0*np.nan:  nan
np.nan == np.nan:  False
np.inf > np.nan:  False
np.nan - np.nan:  nan


In [20]:
# Create a function that adds 100 to something
add_100 = lambda i: i + 100

print('vectorize:')
# Create a vectorized function
vectorized_add_100 = np.vectorize(add_100)

vectorized_add_100(matrix)

vectorize:


array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [21]:
height_weight = [[74.,210.],[71.,189.],[73.,182.],[75.,224.],\
                 [71.,142.],[75.,180.],[69.,165.4],[85.,244.]]
print('height, weight:')
print(height_weight)
np_height_weight = np.array(height_weight)
print(np_height_weight)
print('3rd row:')
print(np_height_weight[2,:])
print('2nd col:')
print(np_height_weight[:,1])
conversion = np.array([0.0254,0.453592])
print('converted height and weight:')
print(conversion*np_height_weight)

height, weight:
[[74.0, 210.0], [71.0, 189.0], [73.0, 182.0], [75.0, 224.0], [71.0, 142.0], [75.0, 180.0], [69.0, 165.4], [85.0, 244.0]]
[[ 74.  210. ]
 [ 71.  189. ]
 [ 73.  182. ]
 [ 75.  224. ]
 [ 71.  142. ]
 [ 75.  180. ]
 [ 69.  165.4]
 [ 85.  244. ]]
3rd row:
[ 73. 182.]
2nd col:
[210.  189.  182.  224.  142.  180.  165.4 244. ]
converted height and weight:
[[  1.8796     95.25432  ]
 [  1.8034     85.728888 ]
 [  1.8542     82.553744 ]
 [  1.905     101.604608 ]
 [  1.8034     64.410064 ]
 [  1.905      81.64656  ]
 [  1.7526     75.0241168]
 [  2.159     110.676448 ]]


In [25]:
#----------- inverse matrices
import time

dims = [50, 100, 1000]

for n in dims:
    print('-----{}x{}-----'.format(n,n))
    mat = np.random.random((n,n))*10
    print('scipy linalg inv:')
    tic = time.process_time()
    inv1 = scipy.linalg.inv(mat)
    toc = time.process_time()
    t_scipy = toc-tic
    print('time used: {}'.format(t_scipy))
    print('numpy linalg inv:')
    tic = time.process_time()
    inv1 = np.linalg.inv(mat)
    toc = time.process_time()
    t_numpy = toc-tic
    print('time used: {}'.format(t_numpy))
    print('t_scipy/t_numpy = {:.3f}'.format(t_scipy/t_numpy))

-----50x50-----
scipy linalg inv:
time used: 0.0
numpy linalg inv:
time used: 0.0


ZeroDivisionError: float division by zero